# Generated by Django 3.1.5 on 2021-01-27 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stadium', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stadium',
        ),
    ]
