# Generated by Django 3.1.5 on 2021-01-28 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_match_tournament'),
        ('stadium', '0003_stadium'),
    ]

    operations = [
        migrations.AddField(
            model_name='stadium',
            name='match',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tournament.match'),
        ),
    ]
